python3 src/Main.py DenseTiny Greedy &
python3 src/Main.py DenseSmall Greedy &
python3 src/Main.py DenseBig Greedy &
python3 src/Main.py Conv1 Greedy &
python3 src/Main.py Conv2 Greedy &
python3 src/Main.py Conv3 Greedy &
python3 src/Main.py DenseTiny Boltz &
python3 src/Main.py DenseSmall Boltz &
python3 src/Main.py DenseBig Boltz &
python3 src/Main.py Conv1 Boltz &
python3 src/Main.py Conv2 Boltz &
python3 src/Main.py Conv3 Boltz &
